name: Sync with aaanh-enterprise/autowin fork

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check if upstream repo
        run: |
          if [ "$GITHUB_REPOSITORY" = "aaanh-enterprise/autowin" ]; then
            echo "This is the downstream repo. No sync is needed."
          fi
      - name: Add remote downstream repo
        run: |
          if [ "$GITHUB_REPOSITORY" != "aaanh-enterprise/autowin" ]; then
            git config --unset-all http.https://github.com/.extraheader && \
            git remote add downstream https://${{github.actor}}:${{secrets.DOWNSTREAM_PAT}}@github.com/aaanh-enterprise/autowin.git
          fi
      - name: Push changes to downstream repo
        run: |
          if [ "$GITHUB_REPOSITORY" != "aaanh-enterprise/autowin" ]; then
            git push -f downstream HEAD:main
          fi
